# Generated by Django 2.1.2 on 2018-11-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('moniker', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('ko_percent', models.IntegerField(default=0)),
                ('sub_percent', models.IntegerField(default=0)),
                ('dec_percent', models.IntegerField(default=0)),
            ],
        ),
    ]
