# Generated by Django 2.1.2 on 2018-11-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighters',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
