# Generated by Django 2.1.2 on 2018-11-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzz', '0002_fighters_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighters',
            name='date_last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
