# Generated by Django 2.1.2 on 2018-11-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzz', '0003_fighters_date_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighters',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fighters',
            name='opponent',
            field=models.ForeignKey(default=1, on_delete='CASCADE', related_name='against', to='zzz.Fighters'),
            preserve_default=False,
        ),
    ]
