# Generated by Django 2.1.2 on 2018-11-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzz', '0004_auto_20181104_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighters',
            name='win',
            field=models.BooleanField(blank=True, default=False, verbose_name='win?'),
        ),
    ]
